name: Release WCR-Doctor

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: zip -r wcr-doctor.zip . -x "*.git*" ".github*" "tests*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: wcr-doctor.zip
          generate_release_notes: true
